apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-servicemonitor
  namespace: default
  labels:
    team: race
spec:
  selector:
    matchLabels:
      app: ui
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
